### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by Jawnnypoo**
@rogerhu This goes along with https://github.com/parse-community/Parse-SDK-Android/pull/628

### CODE REVIEW

**Comment by rogerhu** [comment]
@flovilmart can you give me merge access to this repo too?

**Comment by Jawnnypoo** [comment]
Any word on this @flovilmart ? Would be good to let people know this.

**Review by flovilmart — APPROVED** [review]

**Comment by flovilmart** [comment]
Sorry, missed that one :)

**Comment by rogerhu** [comment]
There's also a Wiki article too that needs updating..

**Comment by Jawnnypoo** [comment]
You mean in the main Parse Android SDK repo? I think only project owners can access/change the wiki

**Comment by rogerhu** [comment]
Updated: https://github.com/parse-community/ParseInterceptors-Android/wiki

**Comment by Jawnnypoo** [comment]
Sweet 👍

**Pull request merged**
